magnetic_declination_radians: 0.1626
yaw_offset: 1.5707
frequency: 10.0
use_odometry_yaw: true
zero_altitude: true
broadcast_cartesian_transform: true
broadcast_cartesian_transform_as_parent_frame: true
wait_for_datum: true
datum: [43.57103, -80.83588, 0.0]
