odom0: /zed2i/zed_node/odom
odom0_config: [true, true, false,
              false, false, true,
              false, false, false,
              false, false, false,
              false, false, false]
odom0_differential: false

#imu0: /imu/data
#imu0_config: [false, false, false,
#              false, false, false,
#              true, true, false,
#              false, false, true,
#              false, false, false]
#imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom
